### ISSUE TITLE
Homepage - servers info is outdated

### ISSUE THREAD

**Issue by mkouba** [cdi-spec/cdi-spec.org#10]
We should either remove this info or keep it up to date. It would be also great to show the CDI version along the implementation.

**Comment by mkouba** [comment]
@antoinesd @LightGuard Do we use this issue tracker at all?

**Comment by antoinesd** [comment]
We should. Some related issues are in JIRA, but it would be a better place do it here. I take this ticket. 

Antoine Sabot-Durand

**Comment by mkouba** [comment]
@antoinesd Thanks! There is no cdi-spec.org-specific JIRA or?

**Comment by antoinesd** [comment]
No specific jira. I saw tickets for website in cdi-spec. Like I said it's better to put them on github. I just have to check them ;)

Antoine Sabot-Durand
